"""init commit

Revision ID: 4dc12e01656f
Revises: 7260499098fc
Create Date: 2022-04-04 23:56:31.072127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc12e01656f'
down_revision = '7260499098fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'))
    op.drop_column('role', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('status', sa.INTEGER(), server_default=sa.text("'1'"), nullable=True))
    op.drop_column('role', 'is_del')
    # ### end Alembic commands ###
