"""init commit

Revision ID: 73bc3e753d18
Revises: 086462ccbfe6
Create Date: 2022-04-01 00:43:45.754937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bc3e753d18'
down_revision = '086462ccbfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
