"""init commit

Revision ID: d3e6a1bf28ae
Revises: 
Create Date: 2022-02-20 12:08:54.063359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e6a1bf28ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('alt_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('pid_id', sa.Integer(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True, comment='类型 menu:模块 button:按钮'),
    sa.Column('title', sa.String(), nullable=False, comment='模块/权限名称'),
    sa.Column('key', sa.String(), nullable=True, comment='模块/权限key'),
    sa.Column('sort', sa.Integer(), server_default='1', nullable=True, comment='排序'),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=True, comment='状态 1.正常 2.禁用'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单权限表'
    )
    op.create_index(op.f('ix_authority_id'), 'authority', ['id'], unique=False)
    op.create_index(op.f('ix_authority_key'), 'authority', ['key'], unique=True)
    op.create_index(op.f('ix_authority_pid_id'), 'authority', ['pid_id'], unique=False)
    op.create_table('enterp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('alt_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('domain', sa.String(), nullable=True, comment='企业域名'),
    sa.Column('name', sa.String(), nullable=True, comment='企业名称'),
    sa.Column('short_name', sa.String(), nullable=True, comment='简称'),
    sa.Column('website', sa.String(), nullable=True, comment='官网'),
    sa.Column('desc', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=True, comment='状态 1.正常 2.禁用 3.到期'),
    sa.Column('expire_at', sa.DateTime(), nullable=True, comment='到期时间'),
    sa.Column('add_user_id', sa.Integer(), nullable=True),
    sa.Column('alt_user_id', sa.Integer(), nullable=True),
    sa.Column('del_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['add_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['alt_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['del_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='企业表'
    )
    op.create_index(op.f('ix_enterp_domain'), 'enterp', ['domain'], unique=True)
    op.create_index(op.f('ix_enterp_id'), 'enterp', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('alt_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('enterp_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True, comment='唯一标识'),
    sa.Column('username', sa.String(), nullable=True, comment='账号'),
    sa.Column('fullname', sa.String(), nullable=True, comment='用户名'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='密码'),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=True, comment='状态 1.正常 2.禁用'),
    sa.Column('is_admin', sa.Integer(), server_default='0', nullable=True, comment='管理员 1.是 0.否'),
    sa.Column('is_superuser', sa.Integer(), server_default='0', nullable=True, comment='系统管理员 1.是 0.否'),
    sa.Column('add_user_id', sa.Integer(), nullable=True),
    sa.Column('alt_user_id', sa.Integer(), nullable=True),
    sa.Column('del_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['add_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['alt_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enterp_id'], ['enterp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_user_del_user_id'), 'user', ['del_user_id'], unique=False)
    op.create_index(op.f('ix_user_enterp_id'), 'user', ['enterp_id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('add_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='创建时间'),
    sa.Column('alt_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='更新时间'),
    sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('enterp_id', sa.Integer(), nullable=True),
    sa.Column('pid_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True, comment='用户组名'),
    sa.Column('desc', sa.String(), nullable=True, comment='备注'),
    sa.Column('path', sa.String(), nullable=True, comment='路径'),
    sa.Column('visible', sa.Integer(), nullable=True, comment='可见范围 1.个人 2.仅分组 3.含下级分组'),
    sa.Column('add_user_id', sa.Integer(), nullable=True),
    sa.Column('alt_user_id', sa.Integer(), nullable=True),
    sa.Column('del_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['add_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['alt_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['enterp_id'], ['enterp.id'], ),
    sa.ForeignKeyConstraint(['pid_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户组表'
    )
    op.create_index(op.f('ix_group_del_user_id'), 'group', ['del_user_id'], unique=False)
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_table('groups_authoritys',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('authority_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authority.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'authority_id')
    )
    op.create_table('users_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_groups')
    op.drop_table('groups_authoritys')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_index(op.f('ix_group_del_user_id'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_enterp_id'), table_name='user')
    op.drop_index(op.f('ix_user_del_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_enterp_id'), table_name='enterp')
    op.drop_index(op.f('ix_enterp_domain'), table_name='enterp')
    op.drop_table('enterp')
    op.drop_index(op.f('ix_authority_pid_id'), table_name='authority')
    op.drop_index(op.f('ix_authority_key'), table_name='authority')
    op.drop_index(op.f('ix_authority_id'), table_name='authority')
    op.drop_table('authority')
    # ### end Alembic commands ###
