"""init commit

Revision ID: eae5fa0e6bc7
Revises: 44b6ef59b1fc
Create Date: 2022-04-04 00:35:47.446958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae5fa0e6bc7'
down_revision = '44b6ef59b1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dict_data', sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'))
    op.add_column('dict_type', sa.Column('is_del', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dict_type', 'is_del')
    op.drop_column('dict_data', 'is_del')
    # ### end Alembic commands ###
